### ISSUE TITLE
Suggested small changes

### ISSUE THREAD

**Issue by timdeschryver** [GooRiOn/Valit#122]
Hi,

First of, great project here (found it via c# digest)! 
After contributing yesterday, I would suggest these small changes - I'm willing to create PRs for the ones that get accepted 😄 

- [x] Small change to `.gitignore` because right now every file from `./tools` will be commited when someone builds the project via the build scripts
- [x] Add [dotnet-watch](https://github.com/aspnet/DotNetTools/tree/dev/src/Microsoft.DotNet.Watcher.Tools), so it would be possible to do `dotnet watch test`
- [x] Add `.editorconfig`
- [x] Add `.gitattributes`?

**Comment by arekbal** [comment]
1. Could you elaborate on this one? I understand the change you are willing to make. I just don't get the reason. Why your build scripts are creating some folder named tools in the root? What if we were to have the same folder in the root under this name? :)
2. I am in favor of this but I wanted to know if it would affect our plans of moving into .net standard assemblies at some point so I added this to our .Tests and added new .net standard dll. It still worked fine. 👍 
3. For tabs as spaces?
4. For EOLs?

**Comment by GooRiOn** [comment]
Arek
1. Cake is creating this folder since we have some external dependencies inside build.cake file (I guess it's xUnit).
3. I agree. Since not everyone is using same IDE, this could be handy 👍

**Comment by timdeschryver** [comment]
@arekbal 

1. See @GooRiOn's answer
2. Thanks for testing it on .net standard
3. The main reasons are tabs as spaces and also indent size. Some others that could be useful are, trim white spaces, charset, end of line, insert final new line.
4. Indeed for EOLs and also merge options i.e. `*.sln -text merge=union`

**Comment by GooRiOn** [comment]
@tdeschryver I guess that both thumbs up mean that you have a green light for your changes :)

**Comment by timdeschryver** [comment]
Okido, I'll create a PR for every change.
