### ISSUE TITLE
Tagging rules for collections - expected behavior

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#123]
As you can see, I added support for collections using ``EnureFor()`` method (PR #120). The issue I noticed is related to the tagging.

The whole concept of supporting collection for either primitive types or nested objects is based on separated implementations of ``IValitRule<TObject, TProperty>`` interface, so:
- ``NestedObjectCollectionValitRule``
- ``CollectionValitRule``

The idea was to aggregate all rules for collections using just one class. Why? Simply because at the point of doing ``EnsureFor()`` we don't have the actual object hence we can't invoke the selector and iterate over the collectiom. So, it's a little bit like "lazy evaluation" when ``Validate()`` method is called an the object is passed to this method. The issue I have is that user may tag the rules inside ``EnsureFor()`` like in the example below:

```csharp
...
.EnsureFor(m => m.Emails, _=>_
    .Required().Tag("A")
    .Email().Tag("B"))
```

But as I wrote, all these rules inside this method are evaluated during the validation. Therefore if user would do something like:

```csharp
...
.EnsureFor(m => m.Emails, _=>_
    .Required().Tag("A")
    .Email().Tag("B"))
.GetTaggedRules()
```

He wouldn't get any result, because what was actually stored inside ``IEnumerable<IValitRule<TObject>>`` was the instance of ``CollectionValitRule`` which was not tagged by the user. 

What really sucks is that actually I have no idea what behavior is correct in this particular scenario. Is this a bug or a feature? :D We need to discuss it until my PR will be merged.

**Comment by GooRiOn** [comment]
@paw3lx  @tdeschryver @arekbal  @dbarwikowski any comments on that one? I'd like to finish this task :/

**Comment by timdeschryver** [comment]
I don't got a strong opinion about this because I'm not 100% sure how the tag system will be used, but here are my 2 cents.

Personally I would create different `IValitRule`s and chain the rules I need instead of using tags, once I actually need it.

Would this also impact the following code?
- `IValitResult result1 = valitRules.Validate("A");`
- `var result1 = rules.Validate(rule => rule.Tags.Any(tag => tag == "A"));`

If so, I would say it should only return if the rule on `IEnumerable` is tagged (for now?).
Another option would be to chain the tags? For example:
```
...
.EnsureFor(m => m.Emails, _=>_
    .Required().Tag("A")
    .Email().Tag("B"))
    .Tag("Emails");
```
The tags would be: `Emails.A` and `Emails.B`, but I suppose that's another discussion 😄

**Comment by GooRiOn** [comment]
Yup, the tagging will impact both of presented scenarios. The issue is that currently we don't have a method which will allow you to tag ``CollectionValitRule`` so we should have something like:

```csharp
.EnsureFor(m => m.Collection, _=>_.Required(), "Tag")
```

This can be done very easily but it implies inconsistency since once we need to call ``Tag()`` and another time just pass it as a parameter :/

**Comment by GooRiOn** [comment]
I think that we can leave it for a now without much carring about tagging collections.  We need to see whether folks will actually use tags :D @arekbal  suggested that we should remove it completely to promote single way of doing something (so as you described creating another chain) instead of multiple alternatives. PR #120 is waiting for you guys 👍
