### ISSUE TITLE
Docs 0.2.0

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#134]
Does anyone could help me with docs for next release? PLEASE!

We need to add:

Inside "Validation rules"

- [x] ``Required()`` for string in "Available validation rules"
- [x] Add bool rules inside "Available validation rules"
- [x] "Validating nested objects" section after "Available validation rules"
- [x] "Validating collections" section after "Validating nested objects"

We also need to add new page called "Valitators" and describe how to create them from:
- [x] ``IValitRulesProvider<TObject>``
- [x] ``IValitRules<TObject>``

**Comment by paw3lx** [comment]
Yeah, sure. I can help with docs inside "Validation rules". I will create PR for this.

**Comment by GooRiOn** [comment]
Great! Then I'll do "Valitators" :) Thanks a lot m8 👍

**Comment by timdeschryver** [comment]
Shouldn't we also add the `Boolean` validation rules?
I can help with writing or proof reading the docs, maybe not today but surely tomorrow.

**Comment by GooRiOn** [comment]
You're right :D

**Comment by GooRiOn** [comment]
@tdeschryver so maybe you could help @paw3lx ?

**Comment by GooRiOn** [comment]
Thx guys :) I'm writing my part right now so new version of docs should be available later this day. We officially released v0.2.0!

THANK YOU!
