### ISSUE TITLE
Asserts in tests

### ISSUE THREAD

**Issue by timdeschryver** [GooRiOn/Valit#135]
I was dabbling around and noticed the `Assert.Equal` methods in the tests are having the wrong signature.
For example:
`Assert.Equal(result.Succeeded, expected);`
should be:
`Assert.Equal(expected, result.Succeeded);`

Is it OK to change this (`Assert.True` and `Assert.False`) by using `Shouldly`?
This way all our tests are written with `Shouldly`.

**Comment by GooRiOn** [comment]
I agree, we should switch fully to shouldly 👍
