### ISSUE TITLE
Broken develop

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#142]
Something weird happend to develop :/ Today I merged develop into master (with rebase) to create a release for version v0.2.0. After a while I realized that I forgot to change the version inside csproj file. I did the change on the develop and I created another PR from develop into master. It turned out that the PR contained all commmits (38) and changes (213) from from 0.2.0 once again. I updated the develop using the UPDATE button and... poof...

PR shown correct change (so just one change inside csproj) but develop has now duplicated commits from 0.2.0... I have no idea what happened! Now comes the best part. I didn't want to have a mess inside master so I squashed all these changes into one commit and merged it into master. So great, master has just one more commit since 0.2.0 merge with updated csproj. I wanted to test what would happend if I'll do some change on the develop once again. I did small change in the README, created new PR from develop to into master and... same story... I contains all commits and changes from 0.2.0... Do you have any idea what caused that? What options we have to fix that. The only one I have is to create new develop from master (tested that and worked as expected).

I'm sorry guys, that's probably my fault... But I swear, I've never had simmilar issue before...

**Comment by GooRiOn** [comment]
I guess it was caused by my stupid rebase...

The options I see are:
- Merge master -> develop and develop ->master to have proper merge done. Byt wi will end up with ~350 commits on both branches with 2 duplicates from 0.2.0
- Create new develop from master but we'll need to create new PR

**Comment by GooRiOn** [comment]
All right, fixed by doing push force on the develop. Now we have same commits on both branches and everything works as expected (verified that). Unfortunately you need to create your PR once again into develop branch. Could you do that @tdeschryver  and @paw3lx? Sorry for that

**Comment by timdeschryver** [comment]
@GooRiOn Done!

**Comment by GooRiOn** [comment]
@tdeschryver thank you, and once again sorry :/ It's embarrassing :/

**Comment by timdeschryver** [comment]
Haha, it was no biggie. 
It can happen to each one of us! 😄

**Comment by paw3lx** [comment]
@GooRiOn I created new PR.

**Comment by GooRiOn** [comment]
@paw3lx  thank you so much, and sorry for all the trouble!

I close the issue :)
