### ISSUE TITLE
Features for v1.0.0

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#145]
Version 0.2.0 was released two days ago, o I think we can start thinking about features for next release. If you have any suggestions, please put them in the comments below :)

For a now we'll definitely,  add:
- [ ] Support for comparing two properties described in #114

**Comment by GooRiOn** [comment]
#146 
#147 
#148

**Comment by timdeschryver** [comment]
Looks great to me!

**Comment by GooRiOn** [comment]
I'd also add #113

**Comment by GooRiOn** [comment]
Does anyone want to do a particular task? Or you'd prefer free pick?

**Comment by timdeschryver** [comment]
I will take a look at #113, if thats OK.

**Comment by GooRiOn** [comment]
Perfect :)

**Comment by GooRiOn** [comment]
All right, since we'll have some breaking changes then I think the best thing we can do is to switch to 1.3.0 version instead of 0.3.0. This will be a clear mark that something changed in the codebase since we'll increment first number in the version. Sounds good?

**Comment by timdeschryver** [comment]
I'm not against it, I surely think it's a good idea for in the feature once we've hit 1.0 and stabilized the codebase.
For now I would just go to 0.3 or maybe even better 1.0?

**Comment by GooRiOn** [comment]
There are two reasons I thought about jumping from 0.2.0 to 1.3.0: 
- when I started the project, I didn't think that we'll have this number of features before version 0.3.0 (not saying about 1.0.0) so it could be hard to add new features for next 7 releases until v1
- 1.0.0 for many folks might looks like the first version 

As far as I know when it comes to versioning the rules are:
- change last number for bug fixing
- change second number for features
- change first number for breaking changes

So in case we have both new features and breaking changes it seems that the best thing we could do is to go straight to the version 1.3.0. But that's just my explenation :D

**Comment by paw3lx** [comment]
Hi guys. I'm little busy right now. I'll be able to do some tasks in the next week. But in the next few days I will try to simplify the code in #114.

**Comment by GooRiOn** [comment]
@paw3lx sure :) No Need to rush :)

**Comment by Jogai** [comment]
Regarding version numbers; according to semver you would make this jump: 0.2.0 -> 1.**0**.0

See https://semver.org/#spec-item-8

And I would love to see some documentation on whats different/unique/better compared to fluentvalidation...

**Comment by GooRiOn** [comment]
@Jogai , I think you're right with the versioning. Thanks for sharing this :) I'll change the milestone and label then.

Regarding docs, I'm not sure whether it's a good idea and what's the point of doing that. It's the developer who decides which library suits more his needs. Both Valit and FV are build completely differently and represent different approaches. But maybe I simply miss something :D

@arekbal , @tdeschryver , @paw3lx ?

**Comment by timdeschryver** [comment]
No strong opinion on this matter, but I agree with you.
Maybe we could add a `Why` section?

**Comment by Jogai** [comment]
Or just a list of features, or use cases where it's applicable.

**Comment by GooRiOn** [comment]
I was quite busy for couple last weeks but I'm back. From what we have I'm going to create 1.0.0-preview1 version. I'll do the same for ASP.NET Core plugin.

@paw3lx what's the status on Autofac plugin? Can I help with that somehow?

**Comment by paw3lx** [comment]
Yea, I'm quite busy too. As you probably saw, I added just one integration - RegisterValit(), which register all Valitators as Singletons. Do you have any idea what we can add here?

**Comment by GooRiOn** [comment]
That actually a good question :D I though that we could also think about auto discovering validators for nested objects in case it was not passed as ``IValitator`` instance inside ``Ensure`` or ``EnsureFor``. But I think we should move this discussion to other repo :)
