### ISSUE TITLE
Validating nested objects - passing the IValitator<TObject>

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#147]
Currently to validate a nested object we need to pass the ``IValitRulesProvider`` object to ``Ensure`` method. Actually we could pass ``IValitator`` object instead since there's no problem with that and we could simply a code even more. Honestly I don't why I didn't do this at the first time :D

**Comment by GooRiOn** [comment]
I'd like to pick this one. Any comments? Shall we do breaking change and switch this to pass valitators instead?

**Comment by timdeschryver** [comment]
I think we can afford to introduce breaking changes atm.

**Comment by GooRiOn** [comment]
ok, then I'll do that !

**Comment by GooRiOn** [comment]
I'll create PR tommorow
