### ISSUE TITLE
Change When predicate

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#16]
Currently `When()` takes `Func<bool>` as the param but as we switched to `IValitRule<TObject,TProperty>` we can change it to `Predicate<TObject>`.

**Comment by arekbal** [comment]
Can I ask what is the advantage of one approach over the other?

**Comment by GooRiOn** [comment]
Well, there isn't but my thought was to be consistent in the code. So, if all predicates are actually `Predicate<TOBject>` I wanted `When()` also to follow this instead of having `Func<bool>`
