### ISSUE TITLE
Support for .NetStandard

### ISSUE THREAD

**Issue by abhilashdonepudi** [GooRiOn/Valit#160]
Any plans for supporting .Net standard. Planning to use this in a Xamarin app.

**Comment by GooRiOn** [comment]
@abhilashdonepudi which .NET Standard do you mean?

**Comment by abhilashdonepudi** [comment]
.NET Standard 2.0

https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/

**Comment by GooRiOn** [comment]
I'll change this in 1.0.0. Expected by the end of this month.

**Comment by GooRiOn** [comment]
1.0.0 has just been published with target framework changed to .NET Standard 2.0 :)
