### ISSUE TITLE
Dont call .Satisfies() condition when .When() returns false

### ISSUE THREAD

**Issue by aletc1** [GooRiOn/Valit#165]
In this code snippet:
```
.Ensure(m => m.Prop, o => o                   
   .Satisfies(prop => condition1)
   .When(x => condition2)
```
In the current version, condition1 and condition2 gets evaluated. But wouldnt be better to not evaluate condition1 if condition2 fails (returns false)?

**Expected result:** condition1 doesnt get evaluated if condition2 evaluates to false

Thank you

**Comment by GooRiOn** [comment]
Good point! I'll look at that.
