### ISSUE TITLE
Question - Dependent Rules

### ISSUE THREAD

**Issue by rmszc81** [GooRiOn/Valit#173]
Good morning @all,

I have one question. 

In the FluentValidation framework by Jeremy Skinner, we can use DependentRules, such as this example here: https://fluentvalidation.net/start#dependent-rules

In Valit, is there any way to achieve this behavior? I really enjoy using Valit but I couldn't realize any way to achieve dependency between rules.

Thank you very much!

Regards,

[],

@rmszc81

**Comment by dbarwikowski** [comment]
@rmszc81 Hey, thanks for question.
Currently there is no support for Dependent Rules. 
Could you put more light on this topic?
I would like to get better understanding in which scenarios this is useful.

Regards,
DB

**Comment by GooRiOn** [comment]
As FV author says:

> "Jeremy’s note: Personally I do not particularly like using DependentRules as I feel it’s fairly hard to read, especially with a complex set of rules. In many cases, it can be simpler to use When conditions to prevent rules from running in certain situations."

So in Valit there the similar way to acheive that using ``When()`` extension which eveluates validation rules only when given predicate returns ``true``.

**Comment by rmszc81** [comment]
@dbarwikowski, @GooRiOn yes, it's true, we can achieve that using the When clause but, in my specific case (and many other projects from past), we have two stages of validation.

1) we validate if the objects has "correct values", not empty, not null, etc.
2) we use these same objects to perform a database query to ensure the 2nd stage of the validation.

Real code, FV:

```
InlineValidatorUser
	.RuleFor(u => u)
	.NotEmpty().WithErrorCode(ErrorCodes.User.ObjectCannotBeEmpty)
	.DependentRules(() =>
	{
		InlineValidatorUser
			.RuleFor(u => u.Id)
			.Cascade(CascadeMode.StopOnFirstFailure)
			.NotEmpty().WithErrorCode(ErrorCodes.User.IdIsNotValid)
			.Must(IsValid).WithErrorCode(ErrorCodes.User.IdDoesNotExists);
		
		InlineValidatorUser
			.RuleFor(u => u.Email)
			.Cascade(CascadeMode.StopOnFirstFailure)
			.NotEmpty().WithErrorCode(ErrorCodes.User.EmailCannotBeEmpty)
			.MinimumLength(8).WithErrorCode(ErrorCodes.User.EmailMinLengthIs8)
			.MaximumLength(64).WithErrorCode(ErrorCodes.User.EmailMaxLengthIs64)
			.EmailAddress().WithErrorCode(ErrorCodes.User.EmailIsNotValid);
	
	}).Must(IsSame).WithErrorCode(ErrorCodes.User.EmailCannotBeChanged);
```
On this example, first, we validate that the user object is not empty/null. 2nd, we validate the Id and the Email address and here's is where the Dependent Rules come in: The IsSame method, who perform a database call, will be run only if the previous validations where successful.

So, this is something that I would like to see in Valit but I understand the complexity over the implementation like this.

Please let me know if I can provide more cases.

Thank you very much!

Regards,

[],

@rmszc81
