### ISSUE TITLE
problems in ValitRuleExtension methods

### ISSUE THREAD

**Issue by arekbal** [GooRiOn/Valit#24]
There are problems in ValitRuleExtensions which surfaced with my PR.

Methods: `Required`, `IsEqualTo`, `IsGreaterThan`, `IsLessThan`, `MinLength`, `MaxLength`, `Matches` handle null improperly.

In `Required`
`p.Equals(default(TProperty))` tries to handle default values such as `int` equal `0` as incorrect 'unrequired' value which is a very specific case... and imho requires specific, strongly typed extensions. Such as `_=>_.Id)(_=>_.IsPositive())`

Inside `IsEqualTo`
Given `x.prop = null` and `y.prop = null`
`Object.Equals(x.prop, y.prop)` makes sense when comparing two objects for similarity without given context.

IMO, user - in case he wants to not let `null` pass - should have to be more specific and add `Required` to handle `null` there. 

Similarly with `IsGreaterThan`. 
When ordering int? it makes sense to make the value null as being lower than 4. What IMO we want from user is to - again - be explicit about handling `null` with `Required` on `Nullable` types or additional param.

And I dont like the way we oversimplify handling of these numbers... (separate overloads in separate namespaces?) `float`s and `double`s can be `NaN`...

Also, Methods `MinLength`, `Maxlength `and `Matches` could handle these string-like types safer and without `typeof` with a string copy from `IEnumerable<char>` such as `new string(p.ToArray())`.

For plain strings I would suggest separate overload in separate namespace.

For instance: 
` public static class ValitRuleStringExtensions
    {
        public static IValitRule<TObject, string> MinLength<TObject>(this IValitRule<TObject, string> rule, int length) where TObject : class
        {
            rule.ThrowIfNull(ValitExceptionMessages.NullRule);
            return rule.Satisfies(p =>
                p.Length >= length);
        }
    }`
there is no magic or casts about it... ;)

Classes with very specific overloads for all the basic types. Drop the `typeof` where possible...

So again I am not sure if these string validation extensions should require themselves input to not be `null`... 
So the question is:
1. `.Required("missing value, Dude").MaxLength(5, "Input Value '{0}' is longer than {1}")`
or just
2. `.MaxLength(5, "Input Value '{0}' is longer than {1} or maybe null?!?")`
or just treat
3. `.MaxLength(5, "Input Value '{0}' is longer than {1}")`
same as calling 
`.Required().MaxLength(5, "Input Value '{0}' is longer than {1}")`
where `Required` gets some default message customisable in "context" configuration.
I think the ideal case for this specific example is to allow both (1 and 3).

**Comment by GooRiOn** [comment]
I agree pretty much with all your statements, but still need to make sure I understood everything, so will contact you after my trip to Denmark. But besides that, we'll probably have to break this down into separated issues.
