### ISSUE TITLE
Remove Required on value types

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#28]
Currently we can do something like this:
```

....
.Ensure(model => model.IntValue)
.Required()
...
```

The problem with the above approach is that we use **`default(TProperty)`** inside the condition. Due to that fact if IntValue equals 0, Required rule is not satisfied. We should change that. The suggested solutions are:

- Add overload for `Required` which takes a "strategy" how 0 should be treated
- Remove Required on value types and add only **`.IsPositive()`** and **`.IsNegative()`** methods
- I also think about something more general like **`.IsNonDefault()`**

I'm open for more suggestions on that one guys ;)

**Comment by arekbal** [comment]
I am against 1. 
All for both 2 and 3. 
With the IsPositive, IsNegative... 
https://math.stackexchange.com/questions/26705/is-zero-positive-or-negative
So maybe do IsPositive(bool zeroIsPositive=false) and same with negative?
Heh... But adding NonZero makes sense.

**Comment by GooRiOn** [comment]
Imho adding flag to the IsPositive and IsNegative is a little bit confusing, because how should we call them?
- zeroIsPositive and zeroIsNegative? or zeroIsPositive for both of them?

Adding NonZero makes much more sense since you can easily define your requirement, so adding:

.IsPositive()
.IsNonZero()

means that you expect a number to be higher than 0, otherwise it can be satisfied also for 0

The problem with zero is that different "types of math" threat it completely different. As far as I remember in discrete mathematics it's positive but in mathematical algebra it's not. 

Soo, so sum it up :D 
I'd go for IsPositive(), IsNegative(), IsNonZero() and assume that if the third is non included then the rule will be satisfied also for 0. Of course we should point that in docs.
