### ISSUE TITLE
Add extension methods for DateTime

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#46]
I noticed that we have very poor support for DateTime. We need couple methods which might be handy for people like:

- IsLaterThan(Datetime dateTime)
- IsEarlierThan(Datetime dateTime)
- IsLaterThanNow()
- IsEarlierThanNow()

**Comment by arekbal** [comment]
Lol... so... TimeSpan, DateTimeOffset and nullable variants.

**Comment by arekbal** [comment]
IsInRange
