### ISSUE TITLE
Add support for message keys

### ISSUE THREAD

**Issue by GooRiOn** [GooRiOn/Valit#5]
We should support adding message keys besides "classic" messages.

Tasks:
- Provide interface for message keys provider
- Add WithMessageKey extension method
- Modify ValitRules, so it can get proper messages inside Validate method

**Comment by arekbal** [comment]
Could you define how you understand Message Key?

**Comment by GooRiOn** [comment]
Key is some sort of string using which we can take the actual message. I thought about something like:

```
public interface IValitMessageProvider
{
    string GetByKey(string key);
}
```

So user can define it's own structure inside the code and implement only this interface. Then when he want to use it inside our code he goes for something like this

```
ValitRules<Model>
.WithMessageProvider(myMessageProvider)
.Ensure(m => m.Age, _=>_
    .Required()
    .WithMessageKey(MyStaticClass.RequiredKeyMessage))
...
```

So, you can keep it in different place rather than hardcoded inside. I know that you could achieve the same without they key, BUT your message proveder could use DB beneath ;)

**Comment by arekbal** [comment]
Could we build it on top of some sort "metadata" system? Metadata as in customized data associated with particular objects.

So we could have some sort of this sudo structure:

```
RuleInstance
      \\
       RuleMetadata
     //              \\
RuleErrorCode         RuleErrorKey
```

Going with this, you would "ask" a provider for message with validation result + rule instance as in smth like:
```
public interface IValitMessageProvider
{
    string GetErrorMessage(IValidator validator, IRule rule, IRuleMetadata metadata, object failedValue);
}
```
Where validator could contain info about field such as validator.FieldName or validator.DisplayName.
rule param might be even unnecesarry... it depends... but we just need that specific metadata related to that rule "instance". But still, we need value which failed to build nice messages.

If you ask, we don't necesarrily have to do this in OOP way.
