### ISSUE TITLE
Add basic tests

### ISSUE THREAD

**Issue by dbarwikowski** [GooRiOn/Valit#7]
Add some basic tests for: 
-Int16 
-Int32 
-Int64 
-UInt16 
-UInt32 
-UInt64 
-Single 
-Double 
-Byte 
-Decimal
-Boolean
-String

**Comment by GooRiOn** [comment]
Should I create another issue for strategies tests ?

**Comment by arekbal** [comment]
That project needs to handle Nullables, as they are so common. Not mentioning of having a way of handling custom Optionals/Results. As these are usually part of service inputs.
